# Generated by Django 3.1.3 on 2022-04-06 09:18

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produtoamostra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoamostra',
            options={},
        ),
        migrations.AddField(
            model_name='produtoamostra',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True),
        ),
        migrations.AlterField(
            model_name='produtoamostra',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True),
        ),
    ]
