# Generated by Django 3.1.3 on 2022-04-06 10:16

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20220406_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, upload_to='produto//%Y/%m/%d'),
        ),
    ]
