version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3305:3305'
    environment:
       MYSQL_DATABASE: 'test_db'
       MYSQL_USER: 'root'
       MYSQL_ROOT_PASSWORD: 'Feagri@019'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/store
    ports:
      - "8000:8000"
    depends_on:
      - db