# Generated by Django 3.1.3 on 2022-05-26 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_auto_20220526_0527'),
        ('ordem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self', to='produto.product'),
        ),
    ]
